site_name: California Open Source Portal Playbook
site_url: https://codecaopensource-playbook.readthedocs.io/en/latest/

repo_url: https://github.com/codecasupport/playbook

theme:
    name: readthedocs

pages:
    - Welcome: README.md
    - Why: why.md
    - Policy: policy.md
    - Feedback: feedback.md
    - About: about.md
    - Community: community.md
    - Platform: platform.md
    - Governance: governance.md
    - Workflow: workflow.md
    - Security: security.md

extra_css:
    - css/extra.css

plugins:
    - search
